const path = {
  PUBLIC: "/",
  HOMEPAGE: "home",
  ADMIN: "/",
  ADMINDASHBOARD: "",
  HOME: "",
  LOGIN: "sign-in",
  PROFILE: "profile",
  COLLECTION: "collection",
  CUSTOMER: "customers",
  LOTTERY: "lottery",
  INFORMATION: "information",
  NAME: "setName/:id",
  GENDER: "setGender/:id",
  BANK: "setBank/:id",
  WITHDRAW: "withdraw/:id",
  HISTORYWITHDRAW: "withdrawalhistory/:id",
  HISTORYDEPOSIT: "depositalhistory/:id",
  SETTING: "setting",
  CREATE_COLLECTION: "collection/new",
  CREATE_LOTTERY: "lottery/new",
  CREATE_CUSTOMER: "customer/new",
  CUSTOMER_DETAIL: "customer/:id",

  COLLECTION_DETAIL: "collection/:id",
  CINEMA_DETAIL: "video/:title/:id/:userId",
  LOTERY: "lottery/:roomId/:userId",
  EDIT_USER: "edit/:id",
};
export default path;
